// Traducciones ES/EN para la plataforma
const translations = {
  es: {
    saludo: "Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni",
    menu_inicio: "Inicio",
    menu_actividades: "Más Actividades",
    menu_directiva: "Directiva",
    menu_contacto: "Contacto y Comunicación",
    menu_juegos: "Juegos",
    menu_material: "Material",
    menu_historia: "Historia Interactiva",
    que_es: "¿Qué es la Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni?",
    que_es_p1: "La Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni es una organización juvenil que tiene el propósito de reducir la tasa de embarazos adolescentes en el departamento del Beni, Bolivia.",
    que_es_p2: "A través de la educación, la sensibilización y el conocimiento acerca de los servicios de salud, la plataforma trabaja para empoderar a los jóvenes y brindarles las herramientas necesarias para tomar decisiones informadas sobre su salud sexual y reproductiva.",
    quienes_somos: "¿Quiénes somos?",
    quienes_somos_p1: "La Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni es una organización juvenil cuyo propósito es reducir el índice de embarazos en adolescentes y disminuir la tasa de VIH/SIDA, así como otras enfermedades de transmisión sexual. La plataforma está conformada por adolescentes y jóvenes del departamento del Beni, quienes trabajan de manera voluntaria y con el firme compromiso de generar un cambio positivo en la sociedad, colaborando con distintas instituciones y organizaciones para alcanzar sus objetivos.",
    que_hacemos: "¿Qué hacemos?",
    que_hacemos_p1: "La Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni trabaja en la promoción de la salud sexual y reproductiva, la prevención de embarazos no deseados y la reducción de la violencia de género. A través de talleres, charlas y actividades comunitarias, buscamos empoderar a los jóvenes para que tomen decisiones informadas sobre su salud.",
    mision: "Nuestra misión",
    mision_p1: "La PDPEAJ-Beni tiene como misión colaborar en la reducción del embarazo adolescente en el departamento del Beni, promoviendo el ejercicio de los derechos sexuales y reproductivos de adolescentes y jóvenes a través de acciones de prevención, educación y sensibilización.",
    vision: "Nuestra visión",
    vision_p1: "La PDPEAJ-Beni tiene como visión ser una plataforma reconocida en todo el departamento por su impacto en la promoción de la salud sexual y reproductiva y la prevención del embarazo en adolescentes y jóvenes, promoviendo el acceso a servicios de salud de calidad, empoderando a la juventud para que tome decisiones informadas sobre su salud, y consolidando una estructura juvenil que fortalezca la atención integral para este grupo poblacional.",
    importancia: "¿Por qué es importante la prevención de embarazos en adolescentes y jóvenes?",
    importancia_p1: "La prevención de embarazos en adolescentes y jóvenes es fundamental para garantizar el bienestar y la salud de las futuras generaciones. Los embarazos no deseados pueden tener un impacto negativo en la vida de los jóvenes, afectando su educación, salud y oportunidades laborales. Además, la prevención de embarazos en adolescentes y jóvenes contribuye a la reducción de la pobreza y la desigualdad de género.",
    a_quienes: "¿A quiénes nos dirigimos?",
    a_quienes_p1: "La Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni se dirige a todos los adolescentes y jóvenes del departamento del Beni. Nuestro objetivo es llegar a todos los jóvenes, independientemente de su situación socioeconómica, para brindarles información y recursos sobre salud sexual y reproductiva.",
    estructura: "¿Cómo se conforma la PDPEAJ-BENI?",
    estructura_p1: "La PDPEAJ-BENI se conforma por una mesa directiva y sus respectivos delegados (los delegados son aquellos miembros que no tienen un cargo específico, pero que participan activamente en las actividades de la plataforma.)",
    estructura_p2: "La mesa directiva está conformada por:",
    presidente: "Presidente",
    vicepresidenta: "Vicepresidenta",
    vicepresidente2: "Vicepresidente 2do",
    delegado_nacional: "Delegado a la Nacional",
    secretario_actas: "Secretario de Actas",
    secretario_alianzas: "Secretario de Alianzas",
    secretaria_comunicacion: "Secretaria de Comunicación",
    secretario_comunicacion: "Secretario de Comunicación",
    vocal1: "Vocal",
    vocal2: "Vocal",
    h3_feria: "Feria De Concientizacion Para La Prevención De Embarazos Adolescentes",
    h3_reestructuracion: "Reestructuración",
    h3_plataforma: "Plataforma Nacional",
    h3_corso: "Corso Preventivo",
    h3_webinar: "Ciclo webinar",
    h3_presentacion: "Presentación Oficial",
    h3_consejo: "Consejo Departamental de la Juventud",
    actividades_titulo: "ACTIVIDADES",
    reestructuracion_texto: "Se realizó la reestructuración de la PDPEAJ-BENI, donde la nueva mesa directiva y los delegados asumieron el compromiso de poner todo su esfuerzo para alcanzar los objetivos de esta gestión. Con energía renovada y muchas ganas, están listos para impulsar cambios positivos y fortalecer el trabajo en beneficio de la juventud.",
    plataforma_nacional_texto: "Durante esta actividad, la PDPEAJ-BENI se unió a las plataformas de los demás departamentos para crear la Plataforma Nacional de Prevención de Embarazos en la Adolescencia y Juventud. Gracias a este encuentro, se formó una mesa directiva nacional con representantes de cada uno de los nueve departamentos, demostrando el compromiso y la unidad de la juventud boliviana en la lucha por un futuro más informado, saludable y con mayores oportunidades.",
    corso_texto: "Durante el Corso Trinitario 2025, la PDPEAJ-BENI estuvo presente con una actividad preventiva pensada especialmente para los jóvenes. Se repartieron métodos anticonceptivos y se compartió información clara y accesible sobre cómo cuidarse y prevenir las enfermedades de transmisión sexual (ETS), demostrando que la diversión también puede ir de la mano con la responsabilidad y el autocuidado.",
    ciclo_webinar_texto: "Durante este ciclo de webinars a nivel nacional, en alianza con las plataformas de <a href=\"https://www.facebook.com/profile.php?id=100064239232991&mibextid=ZbWKwL\" target=\"_blank\" style=\"color:#246b2e; font-weight:bold; text-decoration:underline;\">La Paz</a> y <a href=\"https://www.facebook.com/profile.php?id=61567411175019\" target=\"_blank\" style=\"color:#246b2e; font-weight:bold; text-decoration:underline;\">Potosí</a>, hablamos de un tema que nos toca a todos: las relaciones de pareja. Conversamos sobre cómo son, cómo funcionan y qué hace que una relación sea sana y duradera. Fue un espacio pensado para que los jóvenes puedan entender mejor sus emociones, aprender a comunicarse y fortalecer sus vínculos, siempre con respeto y confianza. Porque estar bien en pareja también es parte de cuidarnos y crecer juntos.",
    presentacion_oficial_texto: "Se presentó oficialmente a los nuevos delegados que, junto con la mesa directiva, serán los encargados de llevar adelante el plan de trabajo para la gestión 2025. Además, estarán al frente de todas las actividades que surjan a lo largo del año, comprometidos con hacer de esta gestión una experiencia dinámica, participativa y llena de aprendizajes.",
    consejo_texto: "La PDPEAJ-BENI participó activamente en <b>\"CONSTRUYENDO PROPUESTAS POR NUESTROS DERECHOS\"</b>, un espacio donde se presentaron diversas propuestas y proyectos de ley con el objetivo de impulsar el desarrollo y fortalecer la participación de los jóvenes en la política. Gracias a este proceso, se conformó oficialmente el Consejo Departamental de la Juventud del Beni, un paso clave para que la voz de las nuevas generaciones tenga más peso y presencia en las decisiones que nos afectan a todos."
    ,
    como_ayudar_titulo: "¿Cómo puedes ayudar?",
    como_ayudar_p1: "Si deseas unirte a la Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni, puedes ponerte en contacto con nosotros a través de nuestras redes sociales o nuestro sitio web.",
    como_ayudar_p2: "También puedes ayudarnos a difundir nuestra misión y visión compartiendo nuestra información con tus amigos y familiares. Cuantas más personas conozcan nuestra plataforma, más impacto podremos tener en la prevención de embarazos en adolescentes y jóvenes.",
    como_ayudar_p3: "Los adolescentes y jóvenes que quieran apoyar y ser participes de esta organización juvenil deben contar con los 15 años cumplidos y hasta un máximo de 23 años para poder ser uno de los miembros de la PDPEAJ-Beni",
    como_contactar_titulo: "¿Cómo puedes contactarnos?",
    como_contactar_p1: "Si deseas obtener más información sobre la Plataforma Departamental de Prevención de Embarazos en Adolescentes y Jóvenes del Beni, puedes ponerte en contacto con nosotros a través de nuestras redes sociales, nuestros números telefónicos o escribiéndonos a nuestro correo electrónico.",
    telefonos_titulo: "Teléfonos de contacto",
    telefono_presidente: "+591 72817484 - Presidente de la PDPEAJ-Beni",
    telefono_vicepresidenta: "+591 71148768 - Vicepresidenta de la PDPEAJ-Beni",
    correo_titulo: "Correo Electrónico",
    correo_email: "plataformadeprevencionbeni@gmail.com",
    redes_titulo: "Redes sociales",
    redes_p1: "Siguenos en nuestras diferentes redes sociales para mantenerte informado acerca de las diferentes actividades que realizamos:"
  },
  en: {
    saludo: "Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni",
    menu_inicio: "Home",
    menu_actividades: "More Activities",
    menu_directiva: "Board",
    menu_contacto: "Contact & Communication",
    menu_juegos: "Games",
    menu_material: "Resources",
    menu_historia: "Interactive Story",
    que_es: "What is the Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni?",
    que_es_p1: "The Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni is a youth organization whose purpose is to reduce the rate of teenage pregnancies in the department of Beni, Bolivia.",
    que_es_p2: "Through education, awareness, and knowledge about health services, the platform works to empower young people and provide them with the necessary tools to make informed decisions about their sexual and reproductive health.",
    quienes_somos: "Who are we?",
    quienes_somos_p1: "The Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni is a youth organization whose purpose is to reduce the rate of teenage pregnancies and decrease the rate of HIV/AIDS and other sexually transmitted diseases. The platform is made up of teenagers and young people from the department of Beni, who work voluntarily and with a strong commitment to generate positive change in society, collaborating with various institutions and organizations to achieve their goals.",
    que_hacemos: "What do we do?",
    que_hacemos_p1: "The Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni works in the promotion of sexual and reproductive health, the prevention of unwanted pregnancies, and the reduction of gender-based violence. Through workshops, talks, and community activities, we seek to empower young people to make informed decisions about their health.",
    mision: "Our mission",
    mision_p1: "PDPEAJ-Beni's mission is to help reduce teenage pregnancy in the department of Beni, promoting the exercise of sexual and reproductive rights of teenagers and young people through prevention, education, and awareness actions.",
    vision: "Our vision",
    vision_p1: "PDPEAJ-Beni's vision is to be a platform recognized throughout the department for its impact on the promotion of sexual and reproductive health and the prevention of pregnancy in teenagers and young people, promoting access to quality health services, empowering youth to make informed decisions about their health, and consolidating a youth structure that strengthens comprehensive care for this population group.",
    importancia: "Why is the prevention of teenage and youth pregnancies important?",
    importancia_p1: "The prevention of teenage and youth pregnancies is essential to ensure the well-being and health of future generations. Unwanted pregnancies can have a negative impact on the lives of young people, affecting their education, health, and job opportunities. In addition, the prevention of teenage and youth pregnancies contributes to the reduction of poverty and gender inequality.",
    a_quienes: "Who is our target audience?",
    a_quienes_p1: "The Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni is aimed at all teenagers and young people in the department of Beni. Our goal is to reach all young people, regardless of their socioeconomic status, to provide them with information and resources on sexual and reproductive health.",
    estructura: "How is PDPEAJ-BENI structured?",
    estructura_p1: "PDPEAJ-BENI is made up of a board of directors and their respective delegates (delegates are those members who do not have a specific position, but who actively participate in the platform's activities.)",
    estructura_p2: "The board of directors is made up of:",
    presidente: "President",
    vicepresidenta: "Vice President",
    vicepresidente2: "Second Vice President",
    delegado_nacional: "National Delegate",
    secretario_actas: "Minutes Secretary",
    secretario_alianzas: "Alliances Secretary",
    secretaria_comunicacion: "Communications Secretary (female)",
    secretario_comunicacion: "Communications Secretary (male)",
    vocal1: "Board Member",
    vocal2: "Board Member",
  h3_feria: "Awareness Fair for the Prevention of Teenage Pregnancies",
  feria_texto: "The <b>1st Awareness Fair for the Prevention of Teenage Pregnancies</b> was held, a key event that brought together several institutions committed to this cause, such as SEDEGES Beni, the NGO Save the Children, the Departmental Directorate of Youth, the Ombudsman's Office, the AIDA Center, and the DNNA of the municipality of Trinidad, among others. The fair had the active participation of different educational units in the city, creating a space for reflection, learning, and awareness about the importance of preventing teenage pregnancy, promoting care and responsibility from youth itself.",
    h3_reestructuracion: "Restructuring",
    h3_plataforma: "National Platform",
    h3_corso: "Preventive Parade",
    h3_webinar: "Webinar Series",
    h3_presentacion: "Official Presentation",
    h3_consejo: "Departmental Youth Council",
    actividades_titulo: "ACTIVITIES",
    reestructuracion_texto: "The restructuring of PDPEAJ-BENI was carried out, where the new board of directors and delegates committed to putting all their effort into achieving the objectives of this term. With renewed energy and great enthusiasm, they are ready to drive positive changes and strengthen work for the benefit of youth.",
    plataforma_nacional_texto: "During this activity, PDPEAJ-BENI joined the platforms of the other departments to create the National Platform for the Prevention of Teenage and Youth Pregnancies. Thanks to this meeting, a national board of directors was formed with representatives from each of the nine departments, demonstrating the commitment and unity of Bolivian youth in the fight for a more informed, healthy, and opportunity-filled future.",
    corso_texto: "During the 2025 Trinitarian Parade, PDPEAJ-BENI was present with a preventive activity especially designed for young people. Contraceptive methods were distributed and clear, accessible information was shared on how to take care of oneself and prevent sexually transmitted diseases (STDs), showing that fun can also go hand in hand with responsibility and self-care.",
    ciclo_webinar_texto: "During this national webinar cycle, in alliance with the platforms of <a href=\"https://www.facebook.com/profile.php?id=100064239232991&mibextid=ZbWKwL\" target=\"_blank\" style=\"color:#246b2e; font-weight:bold; text-decoration:underline;\">La Paz</a> and <a href=\"https://www.facebook.com/profile.php?id=61567411175019\" target=\"_blank\" style=\"color:#246b2e; font-weight:bold; text-decoration:underline;\">Potosí</a>, we talked about a topic that affects us all: relationships. We discussed what they are like, how they work, and what makes a relationship healthy and lasting. It was a space designed for young people to better understand their emotions, learn to communicate, and strengthen their bonds, always with respect and trust. Because being well in a relationship is also part of taking care of ourselves and growing together.",
    presentacion_oficial_texto: "The new delegates were officially presented, who, together with the board of directors, will be responsible for carrying out the work plan for the 2025 term. In addition, they will lead all activities that arise throughout the year, committed to making this term a dynamic, participatory, and learning-filled experience.",
    consejo_texto: "PDPEAJ-BENI actively participated in <b>\"BUILDING PROPOSALS FOR OUR RIGHTS\"</b>, a space where various proposals and bills were presented with the aim of promoting development and strengthening the participation of young people in politics. Thanks to this process, the Departmental Youth Council of Beni was officially formed, a key step for the voice of new generations to have more weight and presence in the decisions that affect us all."
    ,
    como_ayudar_titulo: "How can you help?",
    como_ayudar_p1: "If you want to join the Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni, you can contact us through our social networks or our website.",
    como_ayudar_p2: "You can also help us spread our mission and vision by sharing our information with your friends and family. The more people know about our platform, the greater impact we can have on the prevention of teenage and youth pregnancies.",
    como_ayudar_p3: "Teenagers and young people who want to support and participate in this youth organization must be at least 15 years old and up to a maximum of 23 years old to be a member of PDPEAJ-Beni.",
    como_contactar_titulo: "How can you contact us?",
    como_contactar_p1: "If you want more information about the Departmental Platform for the Prevention of Teenage and Youth Pregnancies of Beni, you can contact us through our social networks, our phone numbers, or by writing to our email address.",
    telefonos_titulo: "Contact phone numbers",
    telefono_presidente: "+591 72817484 - President of PDPEAJ-Beni",
    telefono_vicepresidenta: "+591 71148768 - Vice President of PDPEAJ-Beni",
    correo_titulo: "Email",
    correo_email: "plataformadeprevencionbeni@gmail.com",
    redes_titulo: "Social networks",
    redes_p1: "Follow us on our different social networks to stay informed about the different activities we carry out:"
  }
};

function setLanguage(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
  // Guardar preferencia en localStorage
  localStorage.setItem('lang', lang);
}

// Detectar idioma preferido al cargar
window.addEventListener('DOMContentLoaded', () => {
  const lang = localStorage.getItem('lang') || 'es';
  setLanguage(lang);
});

// Puedes llamar a setLanguage('en') o setLanguage('es') desde un botón o menú
